# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-URjtCmbsVuuK1IF3tct7pvTkI3fXU8
"""

import pandas as pd

df = pd.read_csv('audit_clean.csv')
df.head(5)

#Get all uniques year
df['financial_year_end.year'].unique()

#change year  format from 2010 to 2010-2011
df['financial_year_end.year'] = df['financial_year_end.year'].astype('string')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2011','2010-2011')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2012','2011-2012')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2013','2012-2013')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2014','2013-2014')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2015','2014-2015')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2016','2015-2016')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2017','2016-2017')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2018','2017-2018')
df['financial_year_end.year'] = df['financial_year_end.year'].str.replace('2019','2018-2019')

#creating  a new columns for the content
df['Content'] = '-['+ df['financial_year_end.year'] + ': ' + df['opinion.label'] +'](' + df['opinion.report_url']  + ')'

#now group by  Geography
grouped_df = df.groupby("demarcation.code")

#grouped_lists = grouped_df["opinion.report_url"].apply(list)
grouped_lists = grouped_df["Content"].apply(list)

grouped_lists = grouped_lists.reset_index()

grouped_lists['Content'] = grouped_lists['Content'].apply(lambda x: ' '.join(map(str, x)))
grouped_lists

grouped_lists.to_csv("audit_opinion_v1.csv", index=None)